### ISSUE TITLE
Review handling of 404 exceptions from Ontoserver and undefined results of terminology functions.

### ISSUE THREAD

**Issue by piotrszul** [aehrc/pathling#1096]
In some cases Ontoserver ignores unknown systems/version in some responds with 404.
See: TerminolgySerivceIntegrationTest for more details.

Also, we might want to reconsider the handling of undefined results from terminology operations on collections of codings.
For example for `memberOf` maybe it should be:

[true, undefined] -> true
[false, false, false] -> false

but:

[false, undefined] -> undefined (rather then false)

**Comment by piotrszul** [comment]
This may also include special treatment for version for immutable code systems, which would enhance the scope of subsumes for codings with different versions,  as well as possibly codings with version not know to the terminology server for other operations. 
We would essentially ignore the version information for such systems.

**Comment by johngrimes** [comment]
It looks like Ontoserver returns a `Cache-Control` header with at least a 404, so we could use that.

**Comment by johngrimes** [comment]
Resolved in v6.1.0.
