### ISSUE TITLE
Refactor first function

### ISSUE THREAD

**Issue by johngrimes** [aehrc/pathling#115]
Reimplement the first function as part of the refactored design of the v3 implementation.

Tasks:

- [x] Re-enable AggregateQueryTest#queryWithMathExpression
- [ ] Re-enable AggregateQueryTest#queryWithWhereAsComparisonOperand

**Comment by johngrimes** [comment]
There are two enhancements I think we need to make to the solution as part of this ticket:

1. Preservation of element identity
2. Preservation of element order

Given a collection of given names (e.g. Patient.name.given):

1. Thomas
2. Jude
3. Evelyn
4. Evelyn

We should be able to both preserve the order of these elements, and also preserve the fact that there are two "Evelyn" values. The preservation of order is important for functions such as `first()`, and the preservation of duplicate elements will be important for certain aggregation functions that we have not implemented yet (e.g. `mean()`).

One idea that we have talked about for achieving this is to create an "element identifier" column upon `explode` operations. It would need to be unique within a resource, so it would probably be created as a concatenation with parent element identifiers created from previous `explode` operations.

If we need to aggregate against each individual element, instead of just using the resource identifier, we can use both the resource identifier and the element identifier. This might be a way of fixing #136.

Order can then be enforced by sorting on resource identifier and element identifier. Perhaps we only need to explicitly order when we are using an order-sensitive function such as `first()`.

**Comment by piotrszul** [comment]
This is now only naive implementation of `first()` function without explicit order.
The ordering and identity has been extracted to #158

**Comment by johngrimes** [comment]
Resolved by #156.
