### ISSUE TITLE
Skip validation of display term

### ISSUE THREAD

**Issue by johngrimes** [aehrc/pathling#129]
In Pathling v2, the `memberOf` function uses the `$validate-code` operation, and currently sends through the display term for validation.

This is not desirable, as it puts the burden on the user to ensure that all imported data contains the correct display terms. Validation should be the responsibility of the data transformation process that happens ahead of import to Pathling, not the responsibility of the query engine.

This ticket represents the work to fix this within Pathling 2. This issue is already resolved within Pathling 3, as it uses the ValueSet `$expand` operation.

**Comment by johngrimes** [comment]
@kaicode This has now been fixed in v2.1.1.

**Comment by kaicode** [comment]
Thanks @johngrimes ! I'll upgrade.
