### ISSUE TITLE
Encoding of bundles produces unresolvable references.

### ISSUE THREAD

**Issue by piotrszul** [aehrc/pathling#1434]
When encodeBundle is called on bundles generated by Synthea:
a) the id of resources are set to fullUrl URNs from the entry in the bundle
b) all the references are also using the URNs (above).

For example the 'id' of Patient it's is set to its URN 'urn:uuid:704c9750-f6e6-473b-ee83-fbd48e07fe3f'
And the references to it are also use the same value. (urn:uuid:704c9750-f6e6-473b-ee83-fbd48e07fe3f)

We are unable to resolve there references later, as we currently only support relative references (e.g "Patient/323232").

What should happen is that the resources should keep their original ids (e.g. "Patient/323232") 
and the URN references should be resolved to relative references using the rules described here: https://build.fhir.org/bundle.html#references , before the bundle is encoded.

**Comment by johngrimes** [comment]
Fixed in #1436.
