### ISSUE TITLE
MedDRA terminology support

### ISSUE THREAD

**Issue by alejosv** [aehrc/pathling#1440]
Excellent project !!!

I'm consultant IT engineer in [PAHO](https://www.paho.org/en) to project of [AEFI](https://www.paho.org/en/topics/health-services/aefi-support-tool-causality-assessment) (ESAVI in Spanish) and we have like scope make analytics using the [MedDRA](https://www.meddra.org/)'s terminology.

Exists in your roadmap give support to multiple terminologies?

**Comment by johngrimes** [comment]
Hi @alejosv, thanks for your message!

If you want to use the `memberOf`, `subsumes`/`subsumedBy`, `translate`, `property`, `designation` or `display` functions, you will need to use a FHIR terminology server, such as [Ontoserver](https://ontoserver.csiro.au/site/).

You can use these functions with multiple terminologies, and any terminology that is supported by the FHIR terminology server that you use. Most terminologies can be represented using the FHIR [CodeSystem](https://hl7.org/fhir/R4/codesystem.html) resource and loaded in. [ValueSets](https://hl7.org/fhir/R4/valueset.html) can be used to represent subsets of the codes within your terminologies.

If you don't have a terminology server, you can query terminology in a simple way, i.e. simple equality, fixed sets of codes.

**Comment by johngrimes** [comment]
@alejosv Did this answer your question?

I'll close this now, but feel free to add more comments or create a new issue if you have any further questions.
