### ISSUE TITLE
CountFunctionTest.countsByGrouping() does not verify the result dataset

### ISSUE THREAD

**Issue by piotrszul** [aehrc/pathling#155]
In `CountFunctionTest.countsByGrouping()`
the assertion for expectedDataset is incorrect:
```
  assertThat(expectedDataset)
      .hasRows(expectedDataset);
}
```
When changed to:
```
assertThat(result)
    .selectResult()
    .hasRows(expectedDataset);
```
the test fails.

**Comment by johngrimes** [comment]
Fixed in 2e9a0a15f463bf3fff6a160156bb62f7133150ac - the test in question has now is now performing a selection before the comparison with the expected dataset.
