### ISSUE TITLE
Logging broken by upgrade to SLF4J 2

### ISSUE THREAD

**Issue by johngrimes** [aehrc/pathling#1556]
The recent upgrade of `pathling.slf4jVersion` from 1.7.36 to 2.0.7 has caused logging to stop working.

This commit needs to be reverted in order to fix this issue: 0c6cfca7b4eecccfab69b40a746e22cc35d15156

This issue affects Pathling 6.3.0.

**Comment by jerrin89** [comment]
any alternative solution for above??

**Comment by johngrimes** [comment]
@jerrin89 We've just released v6.3.1 which should solve the problem.

Feel free to reopen this issue if you have any further problems.

**Comment by jerrin89** [comment]
@johngrimes the above V6.3.1 is a SLF4J  version or something else??

**Comment by johngrimes** [comment]
6.3.1 is a Pathling version: https://github.com/aehrc/pathling/releases/tag/v6.3.1

If you are using the server, there is a new image on Docker Hub: https://hub.docker.com/r/aehrc/pathling/tags

**Comment by jerrin89** [comment]
@johngrimes we are not using pathing is there any other way to resolve the issue??Atm on the console log the scenario is showing as passed when it actually failed.
