### ISSUE TITLE
Preservation of element order and identity

### ISSUE THREAD

**Issue by piotrszul** [aehrc/pathling#158]
This is extracted from #115:

There are two enhancements I think we need to make to the solution as part of this ticket:

Preservation of element identity
Preservation of element order

Given a collection of given names (e.g. Patient.name.given):

1. Thomas
2. Jude
3. Evelyn
4. Evelyn

We should be able to both preserve the order of these elements, and also preserve the fact that there are two "Evelyn" values. The preservation of order is important for functions such as `first()`, and the preservation of duplicate elements will be important for certain aggregation functions that we have not implemented yet (e.g. `mean()`).

One idea that we have talked about for achieving this is to create an "element identifier" column upon explode operations. It would need to be unique within a resource, so it would probably be created as a concatenation with parent element identifiers created from previous explode operations.

If we need to aggregate against each individual element, instead of just using the resource identifier, we can use both the resource identifier and the element identifier. This might be a way of fixing #136.

Order can then be enforced by sorting on resource identifier and element identifier. Perhaps we only need to explicitly order at the time of invocation of an order-sensitive function such as `first()`.

**Comment by johngrimes** [comment]
Fixed by #191.
