### ISSUE TITLE
Make order of subexpressions in drill-down expression deterministic

### ISSUE THREAD

**Issue by piotrszul** [aehrc/pathling#160]
I have noticed that the drill down expression are non-deterministic (as far as the ordering of sub-expressions in logical conjunction) as they are de-duplicated using `HashSet` in `DrillDownExpressionBuilder`. Technically not a problem, but makes testing somewhat complicated.

It would make testing easier if the drill down expression were deterministic and easy to infer from the query components.

**Comment by johngrimes** [comment]
I've edited this ticket to remove the part about the deterministic ordering of groupings in the response.

I think that the ordering of groupings in the response should not be significant, and if users want to have them ordered for display purposes then client-side sorting is a good option.

**Comment by piotrszul** [comment]
Yes, but it does make testing more fragile, and possibly the sorting could could be done  on the server side.
That optionally could be specified as another argument to aggression requests with the list or grouping columns that should be used for ordering (and the type of order e.g. asc/desc)

**Comment by johngrimes** [comment]
In the testing we already evaluate aggregate responses in a way that is independent of order - through `JSONAssert`.

In `Assertions.assertJson` we use a `JSONCompareMode` of `NON_EXTENSIBLE`, which means that strict ordering is not enforced, but extra elements are not allowed.

**Comment by johngrimes** [comment]
Ordering of sub-expressions within the drill down expression builder fixed in 4bc04a816956de7cbdb20b57116d989dd71e321c.
