### ISSUE TITLE
Extension content

### ISSUE THREAD

**Issue by johngrimes** [aehrc/pathling#163]
This change will add support for the `extension` FHIRPath function (see [Additional functions](https://hl7.org/fhir/R4/fhirpath.html#functions)).

As part of this, changes will be made to persist extension content upon import to enable its query using the `extension` function.

See also: [Extension content](https://pathling.csiro.au/docs/roadmap.html#extension-content)

**Comment by piotrszul** [comment]
For JSON representation for Extensions for primitive type see here: https://www.hl7.org/fhir/json.html#primitive
(This can be inspiration for SQL schema design).

**Comment by piotrszul** [comment]
@johngrimes  I did some tests with a naive implementation (where the extension are just part of the schema) and the bad new is that it's not going to work for any reasonable extension nesting level. I suspect that the main issue is that the schema for the Extension itself is choice of a number of complex type (at least 30 of them) each of which can again have extensions.
So at level 0 each Extension has say 30 fields, at level 1 ->  900 , and at level 2 ->  27,000 fields and this is a gross underestimation.
Anyway I was not able to produce a schema for Patient at level 2 even with 48GB of  heap - the process fails with OutOfMemory error after a couple of minutes.
The good new is that it's quit apparent this is not going to work, so we can focus on an alternative solution.

**Comment by johngrimes** [comment]
I think we can ignore extensions to `Extension` itself.

The `Extension` complex type can have nested extensions, but we can assume that the primitive elements of `Extension` (`url`, `valueBase64Binary`, `valueBoolean`) cannot be extended.

I've been trying to find where it states this in the spec, because it doesn't make a lot of sense to me that this should be possible. I can't find it, which means you might be technically correct.

Nevertheless, I don't think it makes sense and I don't think we need to cater for it.

**Comment by johngrimes** [comment]
Lets create a new configuration parameter: `pathling.encoders.enableExtensions`, and default it to true.
