### ISSUE TITLE
Consider adding the Spring Boot Actuator package to the server for helpful monitoring features

### ISSUE THREAD

**Issue by chgl** [aehrc/pathling#1671]
The Spring Boot Actuator package (https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html) allows exposing health and telemetry endpoints. This is especially neat when deploying to Kubernetes since it supports liveness- and readiness-probes: https://spring.io/blog/2020/03/25/liveness-and-readiness-probes-with-spring-boot.

To also expose metrics in Prometheus format, an additional dependency on https://mvnrepository.com/artifact/io.micrometer/micrometer-registry-prometheus is required. This can track HTTP request durations, but I believe it doesn't yet work out-of-the-box with the HAPI FHIR Facade.

I'd be happy to add these dependencies in a PR if it seems useful to you as well! - the changes are basically the same as when the HAPI FHIR JPA Starter project introduced the same: https://github.com/hapifhir/hapi-fhir-jpaserver-starter/pull/337 & https://github.com/hapifhir/hapi-fhir-jpaserver-starter/pull/355

**Comment by johngrimes** [comment]
@chgl I think this sounds like a great feature, we would be very happy to work with you on a PR!
