### ISSUE TITLE
Make java jar optional in R and python packages

### ISSUE THREAD

**Issue by piotrszul** [aehrc/pathling#1699]
Currently both python and R packages include `pathling-runtime.jar`, which significantly increases their size (~ 50MB).
While shipping the jar with the packages may simplify running pathling in standalone local mode, it's not being used while running in cluster environments such as 'databricks' when the jar is configures as a cluster library with maven coordinates.

This is to consider the possibility of having a R/python package that does not ship  with the jar but instead (based possibly on a configuration parameter)
- assumes that the jar is already loaded by in the cluster configuration (it can check/verify it's existence and version)
- uses maven coordinates to add the package to the local cluster with the `--packages` option.
- downloads the jar locally and ads it to spark jars; this can possibly best be achieved by creating another R/python packages that just ships the jar.
- allows for explicit configuration of the local jar (possibly with a ENV variable) - can be useful for development env

**Comment by johngrimes** [comment]
Resolved in 6.4.0.
