### ISSUE TITLE
Implementation URL in CapabilityStatement does not respect X-Forwarded-Host

### ISSUE THREAD

**Issue by johngrimes** [aehrc/pathling#19]
We have a problem with caching in AnalyticsServerCapabilities.

If you take a look at one of the `/fhir/metadata` endpoints in production, you will see that `http://localhost:8080` is reported as the implementation URL. This happens even if the `X-Forwarded-Host` and `X-Forwarded-Proto` headers are correctly set.

I think the reason for this is caching within the HAPI RestfulServer implementation with respect to CapabilityStatements. The first request to the CapabilityStatement (which is probably from Docker, not containing the proxy headers) is cached for all subsequent requests.

There does not seem to be an obvious way to disable the caching within the public API of HAPI, i.e. `IServerConformanceProvider`.

**Comment by lawley** [comment]
Yep, HAPI caches the capability stmt by default.  We have code in Ontoserver that avoids this.

Michael

________________________________

**Comment by johngrimes** [comment]
In the newest version of HAPI, the `@Metadata` annotation has a `cacheMillis` parameter, which can be set to 0 to disable caching.
