### ISSUE TITLE
Log out execution time for each AggregateExecutorTest and ParserTest

### ISSUE THREAD

**Issue by johngrimes** [aehrc/pathling#199]
This will allow us to compare the relative performance of the code between different test runs.

**Comment by piotrszul** [comment]
The easiest solution may be to use an JUnit timing extension as descibed here: https://junit.org/junit5/docs/current/user-guide/#extensions-lifecycle-callbacks.

But that would time the entire test, while might be more interested in the time of query execution.  Would that be OK?

**Comment by johngrimes** [comment]
I think timing the entire test would be just fine for now.

**Comment by johngrimes** [comment]
Resolved by #221.
