### ISSUE TITLE
Technical version information lost on deserialisation

### ISSUE THREAD

**Issue by johngrimes** [aehrc/pathling#222]
The current implementation has a limitation relating to the deserialisation of technical versions.

Currently, if you import a resource with technical version information (i.e. `meta.versionId`), it will be available for query but it will not be included in the resource within search results, or any other operation that requires conversion of the data back into a FHIR resource.

This requires enhancement to the encoders to intellligently deserialise the `id` element based upon information within the resource `meta` element.

**Comment by piotrszul** [comment]
@johngrimes  I  have had a quick look at this and I can imagine two ways of fixing this:
1) Revert the changes in encoders and let the in parquet be possibly the versioned one but change the  ResourceReader to make the id column unversioned (using the `substring_index()` function)
2) Change the encoders to save IdType in two columns (just like Decimal) maybe 'id' and 'id_versioned` (or the other way around 'id' and 'unversioned_id`) and use the versioned version for serde and the unversioned one as the origin for the id column in ResourceReader.

**Comment by johngrimes** [comment]
@piotrszul I think the first option is clever, but I feel as though option 2 might be better from a performance perspective.

**Comment by johngrimes** [comment]
@piotrszul Is this implementation tolerant of the absence of the `id_versioned` column, as would be the case in Parquet data that would have been imported prior to this change?

I have tested this change through invoking search on previously imported data, and it seems to work without error - but I thought I would double check.
