### ISSUE TITLE
X-Forwarded-Host appends port to URL

### ISSUE THREAD

**Issue by johngrimes** [aehrc/pathling#279]
When setting the `X-Forwarded-Host` header to `foo.com` on a request to `https://bar.com/fhir/metadata`, the expected behaviour is that the `implementation.url` element contains `https://foo.com/fhir`.

The observed behaviour is that the element contains `https://foo.com:443/fhir`.

**Comment by johngrimes** [comment]
In addition to this, `X-Forwarded-Proto` seems to have no effect.

**Comment by piotrszul** [comment]
@johngrimes  I am not able to reproduce this on the local server (v3.2.0).
In my experience the `implementation.url` is correctly constructed  from, the combination of:
`X-Forwarded-Host`, `X-Forwarded-Proto` and `X-Forwarded-Port`.
In particular the port it added to the `implementation.url` only if `X-Forwarded-Port` is not empty.

Can you provide more details on how to reproduce this issue?

**Comment by piotrszul** [comment]
Just implementation notes:

- the url is constructed by `ApacheProxyAddressStrategy`
- called from `ConformanceProvider.getServerBase()`
-  and created at in `FhirServer`

**Comment by johngrimes** [comment]
That is a very good point - we never needed to set `X-Forwarded-Port` in the past, but maybe an update to a dependency has changed this behaviour.

In that case, maybe the only action needed to close this ticket is an update to the documentation: https://pathling.csiro.au/docs/configuration.html#server-base

It should probably mention `X-Forwarded-Port` as one of the headers that should be set.

**Comment by piotrszul** [comment]
I think this is more the case of what headers are actually set by the load balancer/proxy.
If the LB choses to set `X-Forwarded-Port` that it will appear in the `implementation.url` if not set then not.

It does not appear to be standarised by AWS LB does set it: https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html.

I will make a pull request with the updated documentation.
