### ISSUE TITLE
memberOf  may not work correctly for some codings

### ISSUE THREAD

**Issue by piotrszul** [aehrc/pathling#286]
Current implementation of memberOf relies on strict equality of SimpleCodings tested tested for membership and returned in the intersection from the terminology server.
It appears however that Ontoserver may change the value of the coding version so that the input and output coding are not longer strictly equal.

This can work in both directions, e.g.:
- the request includes unversioned codings and the response versioned codings  (this happens only sometimes, e.g. when two different codings systems are included in the request)
- the request includes versioned codings and the response unversioned codings (this always happens)

Here is a link to the postman collection with two request that illustrate this issue:

https://www.getpostman.com/collections/9328c88ceb7925aa0e58

**Comment by johngrimes** [comment]
It's becoming clear to me that the current implementation of `memberOf` is not going to work for a range of different cases, including:

- Versioned codings / versioned ValueSets, as @piotrszul describes above
- SCT post-coordinated codings
- Case-insensitive codes 

I think the way to reliably fix this is to revert back to the implementation of this method that used `$validate-code`. However, I think that there are a few ways that we can offset the performance difference between it and the current ValueSet `$expand` intersection method:

1. Do away with batching requests, and use a plain GET, which is cacheable.
2. Issue the GET requests in parallel, at a configurable level of parallelism.
3. Use conditional requests and maintain a shared cache of `$validate-code` results keyed on `ETag`.

If we can do this well, it can also provide us with a pattern for an efficient implementation of #366, and also possible further optimisation of other terminology functions such as `subsumes`/`subsumedBy` and `translate`, through caching.

**Comment by johngrimes** [comment]
Following some initial investigations, this is going to be difficult to implement for a number of reasons:

- Performance using `$validate-code`, particularly when not using batch, is currently unacceptable, even with parallelism (using Ontoserver).
- The current implementation of `memberOf` (and the "mapper with preview" pattern in general) does not seem to de-duplicate Codings. This performs quite well with the ValueSet intersection method, but is a problem with the `$validate-code` method.
- Any sort of caching done on terminology requests also brings up the question of when we would invalidate this cache - this needs some more thought.

**Comment by johngrimes** [comment]
I think this will be resolved by #757.

**Comment by johngrimes** [comment]
Resolved in v6.1.0.
