### ISSUE TITLE
Make Coding equality semantics conformant and consistent

### ISSUE THREAD

**Issue by johngrimes** [aehrc/pathling#299]
This change will remove the [CodingsEqual UDF](https://github.com/aehrc/pathling/blob/master/fhir-server/src/main/java/au/csiro/pathling/spark/udf/CodingsEqual.java#L16) and change the equality operation to use strict equality when comparing Coding values.

This aligns with the [FHIRPath specification](https://hl7.org/fhirpath/#equality), and will also align the semantics of the equality operator and the equality used when grouping:

> For complex types, equality requires all child properties to be equal, recursively.

For cases where the user wants to apply more nuance to the interpretation of the Coding values, they should use either [subsumes](https://pathling.csiro.au/docs/fhirpath/functions.html#subsumes)/[subsumedBy](https://pathling.csiro.au/docs/fhirpath/functions.html#subsumedby), or the upcoming [equivalence operators](https://github.com/aehrc/pathling/issues/300) (`~`/`!~`).

**Comment by piotrszul** [comment]
@johngrimes this becomes somewhat problematic for coding literals (<system>|<version>|<code>) as they never include `displayName` or `userSelected` fields, which make them practically unusable, e.g. in the with `contain` or equality operators. Is that what we want?

**Comment by johngrimes** [comment]
I think it is what we want, in service of both conformance to the specification and also semantic consistency across the solution.

Luckily we already have subsumes to mitigate this (which is preferable to contains in most cases anyway, as it promotes correct use of terminology), and we're going to prioritise the work on #300.

**Comment by piotrszul** [comment]
True, but this is more about the coding literals (which I believe are not part of the spec anyway) and how this change will limit their usefulness - maybe the literal should be extended to allow for all fields of coding?
