### ISSUE TITLE
Terminology function: property

### ISSUE THREAD

**Issue by johngrimes** [aehrc/pathling#366]
```
collection<Coding|CodeableConcept> -> property(code: string) : collection<String|Integer|DateTime|Decimal|Coding>
```

This function takes a collection of [Coding](https://pathling.csiro.au/docs/fhirpath/data-types.html#coding) or [CodeableConcept](https://hl7.org/fhir/R4/datatypes.html#CodeableConcept) elements as input, and returns a collection containing the values of the specified property.

Example:

```
Patient.reverseResolve(Condition.subject).code.property('effectiveTime')
```

**Comment by johngrimes** [comment]
We could potentially pre-adopt this R5 expand feature to enable a more efficient implementation: https://ontoserver.csiro.au/docs/6/ext-r5-preadopt-exp.html

**Comment by johngrimes** [comment]
Following the implementation of #757, I think [lookup](https://hl7.org/fhir/codesystem-operation-lookup.html) will be the best way to implement this.

**Comment by piotrszul** [comment]
To simplify the implementation we are going to add the optional second parameter that specifies the type of the property being requested, one of: code | Coding | string | integer | boolean | dateTime | decimal


```
collection<Coding|CodeableConcept> -> property(code: string, [type:string]='string') : collection<String|Integer|DateTime|Decimal|Coding>
```

@johngrimes : does it make sense to have this function on CodeableConcept. I mean we can definitely combine the properties for all codings but is that useful in any way?

**Comment by johngrimes** [comment]
Added in v6.1.0.
