### ISSUE TITLE
decimal encoding does not preserve precision.

### ISSUE THREAD

**Issue by piotrszul** [aehrc/pathling#39]
The spec (http://hl7.org/fhir/datatypes.html) say:

> The precision of the decimal value has significance:
> e.g. 0.010 is regarded as different to 0.01, and the original precision should be preserved
> Implementations SHALL handle decimal values in ways that preserve and respect the precision of the value as represented for presentation purposes

The way we store it now always converts precision to 4 decimal places. This is agains the specification which says that precision should be preserved and 1.0000 is different than 1.00. For currency amounts it adds unnecessary 0s e.g. 22.22 becomes 22.2000 and for some high precision values e.g. from observations drops some decimal places e.g. 0.0232323232 -> 0.0233.

**Comment by piotrszul** [comment]
I have had a look at this issue and unfortunately the user defined datatypes are not public in spark 2.x. They might be made public in 3.x.x  see: https://issues.apache.org/jira/browse/SPARK-7768

I think however that there might be a way around by modifying the schema (and encoders) od elements that have decimal primitives to include an extra field with precision. e.g.: here is the schema for Observation (the relevant part):

``` |-- valueQuantity: struct (nullable = true)
 |    |-- id: string (nullable = true)
 |    |-- value: decimal(12,4) (nullable = true)
 |    |-- value_precision: integer (nullable = true)
 |    |-- comparator: string (nullable = true)
 |    |-- unit: string (nullable = true)
 |    |-- system: string (nullable = true)
 |    |-- code: string (nullable = true)
 |-- valueRange: struct (nullable = true)
 |    |-- id: string (nullable = true)
 |    |-- low: struct (nullable = true)
 |    |    |-- id: string (nullable = true)
 |    |    |-- value: decimal(12,4) (nullable = true)
 |    |    |-- value_precision: integer (nullable = true)
 |    |    |-- comparator: string (nullable = true)
 |    |    |-- unit: string (nullable = true)
 |    |    |-- system: string (nullable = true)
 |    |    |-- code: string (nullable = true)
 |    |-- high: struct (nullable = true)
 |    |    |-- id: string (nullable = true)
 |    |    |-- value: decimal(12,4) (nullable = true)
 |    |    |-- value_precision: integer (nullable = true)
 |    |    |-- comparator: string (nullable = true)
 |    |    |-- unit: string (nullable = true)
 |    |    |-- system: string (nullable = true)
 |    |    |-- code: string (nullable = true)
 |-- valueRatio: struct (nullable = true)
 |    |-- id: string (nullable = true)
 |    |-- numerator: struct (nullable = true)
 |    |    |-- id: string (nullable = true)
 |    |    |-- value: decimal(12,4) (nullable = true)
 |    |    |-- value_precision: integer (nullable = true)
 |    |    |-- comparator: string (nullable = true)
 |    |    |-- unit: string (nullable = true)
 |    |    |-- system: string (nullable = true)
 |    |    |-- code: string (nullable = true)```

So essentially for every `value` field we add a hidden `value_precision` field after it.
In SQL queries then we can still use 'value' as Decimal but the encoders will be aware of extra fields and adjust the scale/precision accordingly.

The schema generation part is easy, but the encoders seem to depend on the order of the fields (not their names) so I need to understand how to fix them.

@johngrimes would that be a reasonable solution?

**Comment by johngrimes** [comment]
Yes, that sounds fine.

Have you thought about what revised values for precision and scale might be appropriate?

**Comment by piotrszul** [comment]
Yes, I think DECIMAL(24, 6) is appropriate. This gives us at least 18 digits with any scale (as per xs:decimal min requirements) as well as the ability to represent up to 6 decimal places, which in terms of coordinates (which the FIHR spec says are most likely the ones that need largest scale) gives as location precision of ~ 10cm. 
I have implemented all the changes, but since the schema all the data need to be re-imported.
