### ISSUE TITLE
Extract operation

### ISSUE THREAD

**Issue by johngrimes** [aehrc/pathling#4]
This change will introduce a new operation called `extract`. This operation is designed for transforming FHIR data into a flattened form, for use within other tools, such as statistical and machine learning models.

The operation takes a set of expressions that define columns in a tabular view of the data. A URL pointing to a delimited text file is returned, which contains the result of executing the expressions against each subject resource.

![Extract operation](https://pathling.csiro.au/images/extract@2x.png)

### Request

The request for the `$extract` operation is a [Parameters](https://hl7.org/fhir/R4/parameters.html) resource containing the following parameters:

- `subjectResource [1..1]` - (code) The subject resource that the expressions within this query are evaluated against. Code must be a member of [http://hl7.org/fhir/ValueSet/resource-types](http://hl7.org/fhir/ValueSet/resource-types).
- `column [1..*]` - An expression which is used to extract a value from each resource.
  - `expression [1..1]` - (string) A FHIRPath expression that defines the column. The context is a single resource of the type specified in the subjectResource parameter. The expression must evaluate to a primitive value. If any columns preceding this column end in an aggregate function, this column expression must also.
  - `label [0..1]` - (string) A short description for the column, for display purposes.
- `filter [0..*]` - (string) A FHIRPath expression that can be evaluated against each resource in the data set to determine whether it is included within the result. The context is an individual resource of the type specified in the subjectResource parameter. The expression must evaluate to a Boolean value. Multiple filters are combined using AND logic.

### Response

The response for the `$extract` operation is a [Parameters](https://hl7.org/fhir/R4/parameters.html) resource containing the following parameters:

- `url [1..1]` - (uri) A URL at which the result of the operation can be retrieved.

**Comment by jnothman** [comment]
Fwiw this can be simulated, perhaps by aggregating with identifier as a grouping field. This currently appears to be a very slow operation.

**Comment by johngrimes** [comment]
Yes, this would be much more efficient with straight selection without any sort of aggregation. I think the implementation for this will be relatively straight forward, it is just another executor class in addition to AggregateExecutor and SearchExecutor, and a HAPI provider to wrap and expose it.

I think that the other reason that we want a dedicated operation is the need to treat the result as unbounded, so that it is practical for use with large datasets. This means making it asynchronous and writing the result somewhere for efficient retrieval, rather than in a synchronous HTTP response.

**Comment by johngrimes** [comment]
I suppose we could potentially optimise this case within the Aggregate operation, if it was useful...
