### ISSUE TITLE
Online demo app: filter issue 

### ISSUE THREAD

**Issue by pazampog** [aehrc/pathling#506]
Hi All,
I started analysing Pathling by making some test with the online demo application. By the way I defined two columns (retriving respectively "gender" and "id") on the Patient resource and everything worked correctly. Now I want to try to apply a filter to get the results on a "range of  id" or even for just one id. So I defined a filter like this:
`where (id='8a6b3acb-cff6-4a81-921b-6e82aa6ad0d7')` 
But I receives a message like this: 
`Filter expression must be of Boolean type: where($this.id = '8a6b3acb-cff6-4a81-921b-6e82aa6ad0d7')`
I read documentation also about FHIRPath and I think the condition si correctly written. Please can you provide me a feedback?
Thx

**Comment by johngrimes** [comment]
Try this: `id = '8a6b3acb-cff6-4a81-921b-6e82aa6ad0d7'`.

You don't need `where` in this context, all you need to do is supply an expression that returns a boolean. Comparing the `id` element to a string literal does this just fine.

Also, you don't need `$this`, as it is implicit that when you refer to an identifier in the root of the expression that you are referring to path from the input context.

**Comment by johngrimes** [comment]
A filter is:

> A FHIRPath expression that can be evaluated against each resource in the data set to determine whether it is included within the result. The context is _an individual resource_ of the subject resource type.

**Comment by johngrimes** [comment]
Let us know if you have any further problems, either by adding to this issue or creating a new one.
