### ISSUE TITLE
Concept translation

### ISSUE THREAD

**Issue by johngrimes** [aehrc/pathling#74]
#### translate

`collection<Coding|CodeableConcept> -> translate(conceptMapUrl: string, reverse = false, equivalence = 'equivalent') : collection<Coding>`

When invoked on a [Coding](https://pathling.csiro.au/docs/fhirpath/data-types.html#coding)-valued element, returns any matching concepts using the ConceptMap specified using `conceptMapUrl`.

The `reverse` parameter controls the direction to traverse the map - `true` results in "source to target" mappings while `false` results in "target to source".

The `equivalence` parameter is a comma-delimited set of values from the [ConceptMapEquivalence](https://www.hl7.org/fhir/R4/valueset-concept-map-equivalence.html) ValueSet, and is used to filter the mappings returned to only those that have an equivalence value in this list.

Example:

```
Condition.code.coding.translate('https://csiro.au/fhir/ConceptMap/some-map', true, 'equivalent,wider').display
```

**Comment by johngrimes** [comment]
@lawley I'd love to get any feedback you might have on this!

**Comment by lawley** [comment]
> conceptMap: either an actual ConceptMap, or a canonical URL reference to a **value set**

That looks like a typo in the spec :-)

**Comment by lawley** [comment]
nice.
I think it would also be useful to have convenience support for `unmapped` such that a code, if it has no translation, passes through, or is replaced by a fixed value.

**Comment by johngrimes** [comment]
This will return "any matching concepts", so if there are no translations the function will result in an empty collection.

I've added in an optional parameter `defaultCoding`, which will allow for a specified Coding to be substituted in this case.

I've also changed the input type to be either Coding or CodeableConcept - in the case of a CodeableConcept, all translations to all Codings would be included in the resulting collection.

**Comment by johngrimes** [comment]
@lawley I have stumbled upon `ConceptMap.group.unmapped`: http://hl7.org/fhir/R4/conceptmap-definitions.html#ConceptMap.group.unmapped

Doesn't this fulfil the requirement we are trying to meet here with the `defaultCoding` parameter?

**Comment by johngrimes** [comment]
We've done a bit of performance testing against Ontoserver that may be helpful for this implementation.

```
Translation of ~8,000 codes using implicit concept maps
---
4 separate batches of ~2,000 operations each, executed serially - 0:19
1 batch of ~8,000 operations - 0:19
~8,000 individual requests, executed serially - 22:00
~8,000 individual requests, executed in parallel with a pool of 1,000 threads - 0:46
```

It seems a single batch per partition will be ideal. There doesn't seem to be much benefit in limiting the batch size, other than avoiding arbitrary limits on request size imposed by front side proxies.

[translate-hist-assoc.zip](https://github.com/aehrc/pathling/files/5670331/translate-hist-assoc.zip)

**Comment by johngrimes** [comment]
There have been some performance improvements to the translate operation in Ontoserver since my last comment, so hopefully we should see much better results than this.

**Comment by piotrszul** [comment]
@johngrimes  just to document what we agreed yesterday with regards to `equivalence` is that only the translation with equivalence explicitly listed in equivalences are included the results.

**Comment by piotrszul** [comment]
@johngrimes do we need to deduplicate the resulting collection or is it OK to include all translation even if they are duplicated.
So say input is `[ A, C, B,  A]`  and the translation `{ A-> [X, Y], B-> [Y]}`.
Should (could) the result be `[ X, Y, Y, X ,Y ]` or should it be `[X,Y]` ?

**Comment by johngrimes** [comment]
> @johngrimes  just to document what we agreed yesterday with regards to `equivalence` is that only the translation with equivalence explicitly listed in equivalences are included the results.
> 
> 

Yep, I think that's a great starting point and we can perhaps later enhance the solution to respect the hierarchy within `ConceptMapEquivalence`.

**Comment by johngrimes** [comment]
> @johngrimes do we need to deduplicate the resulting collection or is it OK to include all translation even if they are duplicated.
> So say input is `[ A, C, B, A]` and the translation `{ A-> [X, Y], B-> [Y]}`.
> Should (could) the result be `[ X, Y, Y, X ,Y ]` or should it be `[X,Y]` ?

No, I do not think we want to de-duplicate the result. In fact, I'm not sure how you would.

If A, B and C are Codings associated with a resource ID (e.g. from `Patient.reverseResolve(Condition.subject).code.coding`), I think the result should look something like:

| resource ID | coding | result |
| ----------- |--------|--------|
| 1           | A      | X      |
| 1           | A      | Y      |
| 1           | C      | null   |
| 1           | B      | Y      |
| 1           | A      | X      |
| 1           | A      | Y      |

Hopefully I understood the question.

**Comment by piotrszul** [comment]
> No, I do not think we want to de-duplicate the result. In fact, I'm not sure how you would.
> 
> If A, B and C are Codings associated with a resource ID (e.g. from `Patient.reverseResolve(Condition.subject).code.coding`), I think the result should look something like:
> 
> resource ID	coding	result
> 1	A	X
> 1	A	Y
> 1	C	null
> 1	B	Y
> 1	A	X
> 1	A	Y
> Hopefully I understood the question.

Yes, that answers my question. Thanks. I think we technically could deduplicate the result with some kind array aggregation but this way it is easier to implement.

**Comment by piotrszul** [comment]
@johngrimes  OK and how should that work for CodeablConcepts? 
Say we have something like this:
| resource ID | eid  | CodeableConcept |
| ----------- |--------|--------|
| 1           | 0    | [A, B]      |
| 1           | 1      | [A, C]     |
| 1           | 2     | [C ] |


What should the result be?

**Comment by johngrimes** [comment]
I think this is what the result should look like:

| resource ID | eid  | CodeableConcept | result |
| ----------- |------|-----------------| ------ |
| 1           | 0    | [A, B]          | X      |
| 1           | 0    | [A, B]          | Y      |
| 1           | 0    | [A, B]          | Y      |
| 1           | 1    | [A, C]          | X      |
| 1           | 1    | [A, C]          | Y      |
| 1           | 1    | [A, C]          | null   |
| 1           | 2    | [C ]            | null   |

I think the result must be a collection of Codings - it doesn't really make sense for a CodeableConcept to encapsulate the results for an input, as they may be different "concepts" (if that makes sense).
