### ISSUE TITLE
Python: 'JavaPackage' object is not callable

### ISSUE THREAD

**Issue by kapsner** [aehrc/pathling#760]
**Describe the bug**
Hi @johngrimes , first of all many thanks for all the awesome enhancements that have been made to the python API in the meantime.

I was upgrading pythling for python to version 5.4.0 and now run into this strange error when trying to create the PathlingContext:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [12], in <cell line: 4>()
      1 import pathling
      2 from pathling import PathlingContext
----> 4 ptl = PathlingContext.create(spark = spark)

File /opt/conda/lib/python3.10/site-packages/pathling/context.py:87, in PathlingContext.create(cls, spark, fhir_version, max_nesting_level, enable_extensions, enabled_open_types, terminology_server_url, token_endpoint, client_id, client_secret, scope, token_expiry_tolerance)
     81 spark = (spark or
     82          SparkSession.getActiveSession() or
     83          SparkSession.builder
     84          .config('spark.jars', find_jar())
     85          .getOrCreate())
     86 jvm: JavaObject = spark._jvm
---> 87 jpc: JavaObject = jvm.au.csiro.pathling.library.PathlingContext.create(
     88         spark._jsparkSession, fhir_version, max_nesting_level, enable_extensions,
     89         enabled_open_types, terminology_server_url, token_endpoint, client_id,
     90         client_secret, scope, token_expiry_tolerance)
     91 return PathlingContext(spark, jpc)

TypeError: 'JavaPackage' object is not callable
```

**To Reproduce**
I have added all steps to reproduce the issue to our demo-kafka-pipline repo here: https://github.com/miracum/demo-kafka-spark-pipeline/blob/master/volume/getting_started_with_pathling_5.4.0-dev1.ipynb

Maybe I am just overseeing something simple here, as it perfectly worked before....

Would be great to hearing from you in this regard.

Best,
Lorenz

**Comment by johngrimes** [comment]
I've made some updates for you: miracum/demo-kafka-spark-pipeline#7

**Comment by kapsner** [comment]
Hi @johngrimes , thank you very very much for your adjustments. The configuration of pathling and spark works perfectly now (sorry that I have missed the documentation, which describes well the steps required to get everything working: https://pathling.csiro.au/docs/encoders#spark-cluster-configuration).
Best, Lorenz

**Comment by johngrimes** [comment]
Glad to hear you got it all working! 🎉

Let me know if you have any more problems.
