### ISSUE TITLE
Error When Enabling Extensions Via Pathling Context

### ISSUE THREAD

**Issue by dtraviszus** [aehrc/pathling#925]
**Describe the bug**

Hey there! When using PathlingContext.Create(), and setting `extensionsEnabled` to `true`, the following error is returned upon using the `encodeBundle` method from PathlingContext to process a bundle of resources.

`java.lang.UnsupportedOperationException: Only code-generated evaluation is supported.
2	at au.csiro.pathling.encoders.InstanceOf.eval(Expressions.scala:85)
3	at org.apache.spark.sql.catalyst.expressions.If.eval(conditionalExpressions.scala:68)
4	at org.apache.spark.sql.catalyst.expressions.objects.Invoke.eval(objects.scala:381)
5	at org.apache.spark.sql.catalyst.expressions.Alias.eval(namedExpressions.scala:168)
6	at org.apache.spark.sql.catalyst.expressions.InterpretedUnsafeProjection.apply(InterpretedUnsafeProjection.scala:90)
7	at org.apache.spark.sql.catalyst.expressions.InterpretedUnsafeProjection.apply(InterpretedUnsafeProjection.scala:34)
8	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
9	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
10	at org.apache.spark.util.Utils$.getIteratorSize(Utils.scala:1891)
11	at org.apache.spark.rdd.RDD.$anonfun$count$1(RDD.scala:1253)
12	at org.apache.spark.rdd.RDD.$anonfun$count$1$adapted(RDD.scala:1253)
13	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2254)
14	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
15	at org.apache.spark.scheduler.Task.run(Task.scala:131)
16	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
17	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1462)
18	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
19	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
20	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
21	at java.base/java.lang.Thread.run(Thread.java:829)`

This in an environment with Spark 3.2 and Scala 2.12.

**To Reproduce**

See Above

**Expected behavior**

I would have expected the bundle to have been processed into data frames as it is when `extensionsEnabled` is false.

Are there any ideas as to how I could get around this? Or what I'm doing wrong? Thanks!

**Comment by johngrimes** [comment]
Thanks for sending this through!

Do you have a bundle that you can share that reproduces the problem (which doesn't contain any private information)?

**Comment by johngrimes** [comment]
Hi @dtraviszus,

I'm having a bit of trouble reproducing this.

Would you mind providing a bit more information about the execution environment?

I am running Pathling 5.4.0 on Spark 3.2.1 (Scala 2.12) on Databricks (Databricks Runtime 10.4 LTS), with Java 11.

This is the code I am using (within a Scala notebook):

```scala
import au.csiro.pathling.library.PathlingContext

val pc = PathlingContext.create(spark, null, null, true, null, null, null, null, null, null, null)

val bundles = spark.read.option("wholetext", value = true).text("s3://pathling-demo/staging/support/925.Bundle.json")
bundles.show()

val encoded = pc.encodeBundle(bundles, "Condition")
encoded.select("_extension").show()
```

Are you running this on your computer, within a Docker image, or using some cloud-based environment?

**Comment by johngrimes** [comment]
Hi @dtraviszus, I'm closing this now as we haven't heard from you.

Feel free to re-open if you have any more problems.
